/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pesanan_bryant;

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Administrator
 */
public class tambah_menu extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet foodResult = null;
    ResultSet drinkResult = null;
    PreparedStatement foodPrepState = null;
    PreparedStatement drinkPrepState = null;
    Statement newFoodState;
    Statement newDrinkState;

    /**
     * Creates new form pesanan_admin
     */
    public tambah_menu() {
        initComponents();
        connection();
        display();
    }

    void foodClear() {
        foodNameInput.setText(null);
        foodPriceInput.setValue(0);
    }
    
    void drinkClear() {
        drinkNameInput.setText(null);
        drinkPriceInput.setValue(0);
    }
    
    void connection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/pesanan_bryant";
            String user = "root";
            String pass = "";
            
            conn = DriverManager.getConnection(url, user, pass);
            
            newFoodState = conn.createStatement(foodResult.TYPE_SCROLL_SENSITIVE, foodResult.CONCUR_UPDATABLE);
            newDrinkState = conn.createStatement(drinkResult.TYPE_SCROLL_SENSITIVE, drinkResult.CONCUR_UPDATABLE);
            
            foodResult = newFoodState.executeQuery("SELECT * FROM makanan");
            drinkResult = newDrinkState.executeQuery("SELECT * FROM drink");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.exit(0);
        }
    }
    
    void display() {
        try {
            String foodQuery = "SELECT * FROM makanan";
            String drinkQuery = "SELECT * FROM drink";

            foodPrepState = conn.prepareStatement(foodQuery);
            drinkPrepState = conn.prepareStatement(drinkQuery);

            foodResult = foodPrepState.executeQuery();
            drinkResult = drinkPrepState.executeQuery();
            
            foodTable.setModel(DbUtils.resultSetToTableModel(foodResult));
            drinkTable.setModel(DbUtils.resultSetToTableModel(drinkResult));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        drinkTable = new javax.swing.JTable();
        foodClearButton = new javax.swing.JButton();
        foodDeleteButton = new javax.swing.JButton();
        foodEditButton = new javax.swing.JButton();
        foodSaveButton = new javax.swing.JButton();
        drinkEditButton = new javax.swing.JButton();
        drinkClearButton = new javax.swing.JButton();
        drinkSaveButton = new javax.swing.JButton();
        drinkDeleteButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        foodNameInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        drinkNameInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        foodPriceInput = new javax.swing.JSpinner();
        drinkPriceInput = new javax.swing.JSpinner();
        foodId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        drinkId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tambah Makanan dan Minuman");

        foodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nama Makanan", "Harga Makanan"
            }
        ));
        foodTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(foodTable);

        drinkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nama Minuman", "Harga Minuman"
            }
        ));
        drinkTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drinkTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(drinkTable);

        foodClearButton.setText("Clear");
        foodClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodClearButtonActionPerformed(evt);
            }
        });

        foodDeleteButton.setText("Hapus");
        foodDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodDeleteButtonActionPerformed(evt);
            }
        });

        foodEditButton.setText("Edit");
        foodEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodEditButtonActionPerformed(evt);
            }
        });

        foodSaveButton.setText("Simpan");
        foodSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodSaveButtonActionPerformed(evt);
            }
        });

        drinkEditButton.setText("Edit");
        drinkEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkEditButtonActionPerformed(evt);
            }
        });

        drinkClearButton.setText("Clear");
        drinkClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkClearButtonActionPerformed(evt);
            }
        });

        drinkSaveButton.setText("Simpan");
        drinkSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkSaveButtonActionPerformed(evt);
            }
        });

        drinkDeleteButton.setText("Hapus");
        drinkDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkDeleteButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Makanan");

        jLabel6.setText("Harga Makanan");

        jLabel3.setText("Makanan");

        jLabel4.setText("Minuman");

        jLabel5.setText("Nama Minuman");

        jLabel7.setText("Harga Minuman");

        foodId.setEnabled(false);

        jLabel8.setText("ID Makanan");

        drinkId.setEnabled(false);

        jLabel9.setText("ID Minuman");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(foodSaveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(foodEditButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(foodDeleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(foodClearButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(foodPriceInput)
                                    .addComponent(foodNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(foodId, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(drinkPriceInput))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(drinkNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(drinkSaveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(drinkEditButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(drinkDeleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(drinkClearButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(drinkId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(170, 170, 170))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(280, 280, 280))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drinkNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drinkPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drinkSaveButton)
                            .addComponent(drinkEditButton)
                            .addComponent(drinkDeleteButton)
                            .addComponent(drinkClearButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(foodId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(drinkId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(foodSaveButton)
                            .addComponent(foodEditButton)
                            .addComponent(foodDeleteButton)
                            .addComponent(foodClearButton))
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void foodClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodClearButtonActionPerformed
        // TODO add your handling code here:
        foodClear();
    }//GEN-LAST:event_foodClearButtonActionPerformed

    private void foodDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodDeleteButtonActionPerformed
        // TODO add your handling code here:
        try {
            connection();
            newFoodState = conn.createStatement();
            String query = "DELETE FROM makanan WHERE food_id = '"+foodId.getText()+"'";
            newFoodState.executeUpdate(query);
            display();
            newFoodState.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Makanan berhasil dihapus!");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_foodDeleteButtonActionPerformed

    private void foodEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodEditButtonActionPerformed
        // TODO add your handling code here:
        try{
            connection();
            newFoodState = conn.createStatement();
            String query = "UPDATE makanan SET food_name = '"+foodNameInput.getText()+"', price = '"+foodPriceInput.getValue()+"' WHERE food_id = '"+foodId.getText()+"'";
            newFoodState.executeUpdate(query);
            display();
            newFoodState.close();
            conn.close();
            foodClear();
            JOptionPane.showMessageDialog(null, "Makanan berhasil diedit!");
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_foodEditButtonActionPerformed

    private void foodSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodSaveButtonActionPerformed
        // TODO add your handling code here:
        try{
            connection();
            newFoodState = conn.createStatement();
            String query = "INSERT INTO makanan VALUE(NULL,'"+foodNameInput.getText()+"','"+foodPriceInput.getValue()+"')";
            newFoodState.executeUpdate(query);
            display();
            newFoodState.close();
            conn.close();
            foodClear();
            JOptionPane.showMessageDialog(null, "Makanan berhasil disimpan!");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_foodSaveButtonActionPerformed

    private void drinkEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkEditButtonActionPerformed
        // TODO add your handling code here:
        try{
            connection();
            newDrinkState = conn.createStatement();
            String query = "UPDATE drink SET drink_name = '"+drinkNameInput.getText()+"', price = '"+drinkPriceInput.getValue()+"' WHERE drink_id = '"+drinkId.getText()+"'";
            newDrinkState.executeUpdate(query);
            display();
            newDrinkState.close();
            conn.close();
            drinkClear();
            JOptionPane.showMessageDialog(null, "Minuman berhasil diedit!");
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_drinkEditButtonActionPerformed

    private void drinkClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkClearButtonActionPerformed
        // TODO add your handling code here:
        drinkClear();
    }//GEN-LAST:event_drinkClearButtonActionPerformed

    private void drinkSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkSaveButtonActionPerformed
        // TODO add your handling code here:
        try{
            connection();
            newDrinkState = conn.createStatement();
            String query = "INSERT INTO drink VALUE(NULL,'"+drinkNameInput.getText()+"','"+drinkPriceInput.getValue()+"')";
            newDrinkState.executeUpdate(query);
            display();
            newDrinkState.close();
            conn.close();
            drinkClear();
            JOptionPane.showMessageDialog(null, "Minuman berhasil disimpan!");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_drinkSaveButtonActionPerformed

    private void drinkDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkDeleteButtonActionPerformed
        // TODO add your handling code here:
        try {
            connection();
            newDrinkState = conn.createStatement();
            String query = "DELETE FROM drink WHERE drink_id = '"+drinkId.getText()+"'";
            newDrinkState.executeUpdate(query);
            display();
            newDrinkState.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Minuman berhasil dihapus!");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_drinkDeleteButtonActionPerformed

    private void foodTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodTableMouseClicked
        // TODO add your handling code here:
        try {
         connection();
         int row = foodTable.getSelectedRow();
         String clickTable=(foodTable.getModel().getValueAt(row, 0).toString());
         Statement tempFoodState = conn.createStatement();
         ResultSet tempFoodResult = tempFoodState.executeQuery("SELECT * FROM makanan WHERE food_id='"+clickTable+"'");
         if (tempFoodResult.next()) {
            String id = tempFoodResult.getString("food_id");
            foodId.setText(id);
            String foodName = tempFoodResult.getString("food_name");
            foodNameInput.setText(foodName);
            String foodPrice = tempFoodResult.getString("price");
            foodPriceInput.setValue(Integer.parseInt(foodPrice));
         }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_foodTableMouseClicked

    private void drinkTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drinkTableMouseClicked
        // TODO add your handling code here:
        try {
         connection();
         int row = drinkTable.getSelectedRow();
         String clickTable=(drinkTable.getModel().getValueAt(row, 0).toString());
         Statement tempDrinkState = conn.createStatement();
         ResultSet tempDrinkResult = tempDrinkState.executeQuery("SELECT * FROM drink WHERE drink_id='"+clickTable+"'");
         if (tempDrinkResult.next()) {
            String id = tempDrinkResult.getString("drink_id");
            drinkId.setText(id);
            String drinkName = tempDrinkResult.getString("drink_name");
            drinkNameInput.setText(drinkName);
            String drinkPrice = tempDrinkResult.getString("price");
            drinkPriceInput.setValue(Integer.parseInt(drinkPrice));
         }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_drinkTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambah_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambah_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambah_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambah_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambah_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drinkClearButton;
    private javax.swing.JButton drinkDeleteButton;
    private javax.swing.JButton drinkEditButton;
    private javax.swing.JTextField drinkId;
    private javax.swing.JTextField drinkNameInput;
    private javax.swing.JSpinner drinkPriceInput;
    private javax.swing.JButton drinkSaveButton;
    private javax.swing.JTable drinkTable;
    private javax.swing.JButton foodClearButton;
    private javax.swing.JButton foodDeleteButton;
    private javax.swing.JButton foodEditButton;
    private javax.swing.JTextField foodId;
    private javax.swing.JTextField foodNameInput;
    private javax.swing.JSpinner foodPriceInput;
    private javax.swing.JButton foodSaveButton;
    private javax.swing.JTable foodTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
